# Travis-CI for Drupal 8.

language: php
php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
  # Set up the Github OAuth token.
  # Please change this in your own fork.
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json
  # Try to use composer to create a Drupal 8 project.
  - composer create-project drupal/drupal drupal 8.0.*@dev --no-progress
  # Create a database.
  - mysql -e 'create database drupal;'

script:
  - cd drupal
  # Allow PHPUnit to fail-out the tests before too much time goes by.
  - ./vendor/bin/phpunit -c core/
  # Use run-tests.sh with --keep-results to avoid 2006 error.
  # Only run one test to keep from timing out.
  - php ./core/scripts/run-tests.sh --sqlite test.sqlite --dburl mysql://travis:@localhost/drupal --class 'Drupal\system\Tests\Entity\EntityFieldTest'
